name: ZMK Build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4

      - name: Build firmware using ZMK container
        container:
          image: zmkfirmware/zmk-build-arm:stable
        run: |
          west init -l .
          west update
          west zephyr-export

          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=my_keyboard

          cp build/zephyr/zmk.uf2 firmware.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: firmware.uf2