name: ZMK Build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
      - name: Checkout config repo
        run: |
          git clone https://git.gekkojr.me/gekko/zmk-config .
          git fetch --prune --unshallow || true

      - name: Initialize west (pointing to this repo as config)
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=my_keyboard
          cp build/zephyr/zmk.uf2 firmware.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zmk-firmware
          path: firmware.uf2